
# VCOM14: ¿Qué sensor realizó cada observación de anclaje?

PREFIX edintvehcom: <https://edint.es/def/vehiculos-compartidos#>
PREFIX sosa: <http://w3.org/ns/sosa/>

SELECT ?obs ?sensor
WHERE {
  ?obs a edintvehcom:DockObservation ;
       sosa:madeBySensor ?sensor .
}