
#VCOM04: ¿Qué puntos de paso tiene cada trayecto?

PREFIX edintvehcom: <https://edint.es/def/vehiculos-compartidos#>

SELECT ?route ?waypoint
WHERE {
  ?route a edintvehcom:Route ;
         edintvehcom:hasWaypoint ?waypoint .
}