
# VCOM05: ¿Qué estaciones existen, quién las opera  y en que estado están?

PREFIX edintvehcom: <http://vocab.linkeddata.es/datosabiertos/def/transporte/vehiculos-compartidos#>
PREFIX schema: <http://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?station ? operator ?operatorLabel ?state ?stateLabel
WHERE {
  ?station a edintvehcom:SharedVehicleStation .
  
  OPTIONAL {
    ?station edintvehcom:operatedBy ?operator .
    ?operator rdfs:label ?operatorLabel .
  }
  
  OPTIONAL {
    ?station edintvehcom:stationState ?state .
    ?state skos:prefLabel ?stateLabel .
  }
}