
#VCOM06: ¿Qué estaciones están operadas por una organización concreta?

PREFIX edintvehcom: <https://edint.es/def/vehiculos-compartidos#>

SELECT ?station
WHERE {
  ?station a edintvehcom:SharedVehicleStation ;
           edintvehcom:operatedBy <URI_ORGANIZACION> .
}