
# VCOM08: ¿En qué estado están los vehiculos compartidos registrados?

PREFIX edintvehcom: <http://vocab.linkeddata.es/datosabiertos/def/transporte/vehiculos-compartidos#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?vehicle ?state
WHERE {
  ?vehicle a edintvehcom:SharedVehicle ;
           edintvehcom:vehicleState ?state .
    OPTIONAL {?state skos:prefLabel ?stateLabel }
  ?state 
}