
# VCOM02: ¿Qué trayectos ha realizado un vehículo concreto?

PREFIX edintvehcom: <https://edint.es/def/vehiculos-compartidos#>

SELECT ?route
WHERE {
  ?route a edintvehcom:Route ;
         edintvehcom:madeByVehicle <URI_DEL_VEHICULO> .
}