
# VCOM09: ¿Cuáles son los vehículos con estado X, propulsión Y y tipo Z?

PREFIX edintvehcom: <https://edint.es/def/vehiculos-compartidos#>
PREFIX edintveh: <https://edint.es/def/censo-vehiculos#>

SELECT ?vehicle
WHERE {
  ?vehicle a edintvehcom:SharedVehicle ;
  # X, Y, Z deben ser URIs de conceptos SKOS, no literales
           edintvehcom:vehicleState <URI_ESTADO_X> ;
           edintvehcom:propulsionSystemType <URI_PROPULSION_Y> ;
           edintveh:vehicleType <URI_TIPO_Z> .
}


