
#VCOM01: ¿Qué vehículos compartidos han realizado trayectos?

PREFIX edintvehcom: <https://edint.es/def/vehiculos-compartidos#>

SELECT DISTINCT ?vehicle
WHERE {
  ?route a edintvehcom:Route ;
         edintvehcom:madeByVehicle ?vehicle .
}
